name: Terraform Drift Detection

on:
  schedule:
    - cron: '0 3 * * *'  # Every day at 03:00 UTC
  workflow_dispatch:     # Manual trigger option

jobs:
  detect-drift:
    runs-on: ubuntu-latest
    name: Check for Terraform Drift

    env:
      AWS_REGION: us-east-1  # Adjust as needed
      TF_IN_AUTOMATION: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.1  # or your preferred version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: Day-8-Migration-DriftDetection/Scenerio-2

      - name: Terraform Refresh-Only Plan
        id: plan
        run: |
          terraform plan -refresh-only -no-color -out=tfplan || echo "Terraform plan completed"
          terraform show -no-color tfplan > plan_output.txt
        working-directory: Day-8-Migration-DriftDetection/Scenerio-2

      - name: Check for Drift in Plan Output
        run: |
          if grep -q "Note: Objects have changed outside of Terraform" Day-8-Migration-DriftDetection/Scenerio-2/plan_output.txt; then
            echo "❌ Drift detected!"
            cat Day-8-Migration-DriftDetection/Scenerio-2/plan_output.txt
            exit 1
          else
            echo "✅ No drift detected."
          fi
